### ISSUE TITLE
Setup callback URL for Android. Help guys please! 

### ISSUE THREAD

**Issue by dkfl1995** [GoldenOwlAsia/react-native-twitter-signin#101]
Hey, I chose this package to setup twitter signin. Thank you, first of all, for your job) 
For be more clear, I tell you what I did to setup this package on react-native android part of app.
1. installed "npm i react-native-twitter-signin --save && react-native link react-native-twitter-signin"
2. Added lines to app: build.gradle, included into setting.gradle,added package invokation into mainapplication.java.
3. Did method with imported " import {RNTwitterSignIn} from 'native-modules'.
Also generated twitter app with name "sunyainnov". And generated consumer key and secret. 
Added callback URL into twitter apps settings:
-       twitterkit-jtbxxxxxxxxxxxxxxxxxx7i://	
-       twitterkit://	
-       twittersdk://	
-       https://google.com/auth/twitter/callback.
Started to RNTwitterSignIn.init with consumers and login() but 
method promise throws to error. If debug into Android Studio logcat it sees that bad stucking error:

> com.foodilog E/Twitter: Invalid json: <?xml version="1.0" encoding="UTF-8"?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>

So what guys should I do to let my application signin work with twitter? Im stuck with this for a 2 days long. Im tired for a little to be without result.

Maybe something misconfigured, or did not set up yet, or not installed please tell me.

**Comment by DannyAziz** [comment]
Did you work this out? Having the same issue with iOS

**Comment by dkfl1995** [comment]
It was urgent to solve issue, so due to lack of ways to solve it with react-native-twitter-signin package, I changed the to package react-native-oauth and setup the callback url to http://localhost/twitter as it explained at thats docs. And it started to work correctly

**Comment by Cawfree** [comment]
Twitter configuration [has changed](https://twittercommunity.com/t/callback-url-not-approved-but-worked-for-months/107261/20) since GDPR; for example, it's no longer possible to specify _callback locking_. This had been announced for around a month prior to implementation. With `react-native-twitter-signin`, I was receiving this [error](https://twittercommunity.com/t/http-request-failed-status-401/73906).

It seems to have had an adverse effect on this library, but it can be fixed:
  - I regenerated a new set of login tokens (I don't really think this is required but I did it).
  - Sanity checked the Callback URL. (It hadn't been changed.)
  - Finally, I enabled `Request E-Mail Permissions` in my App > Permissions > Additional Permissions.

Enabling E-Mail permissions I believe is the trick, because these changes seem to have enforced more precision around how the login transaction is made. You can see that in `react-native-twitter-signin`, it uses `twitterAuthClient.requestEmail`; so without this permission enabled, the request fails.

To make things worse, you'll need to wait a little while before the effect takes place, so remember to be patient. I had to wait around thirty minutes, so put your feet up or something. You've been working hard.

**Comment by Parmar-Bansi** [comment]
> It was urgent to solve issue, so due to lack of ways to solve it with react-native-twitter-signin package, I changed the to package react-native-oauth and setup the callback url to http://localhost/twitter as it explained at thats docs. And it started to work correctly

can you deep explain me..??
