### ISSUE TITLE
Twitter signin error: Possible Unhandled promise rejection

### ISSUE THREAD

**Issue by aryalprakash** [GoldenOwlAsia/react-native-twitter-signin#127]
I've setup `react-native-twitter-signin` as like in documentation and works perfectly on Android. But I'm getting this error on iOS.
`Possible Unhandled Promise Rejection (id: 1): Error: Twitter signin error.
![Screen Shot 2019-03-29 at 1 30 16 PM](https://user-images.githubusercontent.com/3658290/55217295-4b2db680-5227-11e9-8b43-5d8ab4b2c276.png)

**Comment by aryalprakash** [comment]
I added `twitterkit-CONSUMER_KEY://` to callback url and got this working on iOS too.

**Comment by joeljerushan** [comment]
@aryalprakash can you tell me where you have added `twitterkit-CONSUMER_KEY://` ?

**Comment by adrrian17** [comment]
> @aryalprakash can you tell me where you have added `twitterkit-CONSUMER_KEY://` ?

It needs to be added on the callbacks URLs on your Twitter app

**Comment by karta1502545** [comment]
Note for iOS developers:
I try to use this package for a day and the following setting works fine on my iPhone:
I keep the Facebook login settings so that you can better know how to add twitter login.
So you can just ignore the Facebook login settings.

I refer the following issues to come up with this solution.
https://github.com/GoldenOwlAsia/react-native-twitter-signin/issues/62
https://github.com/GoldenOwlAsia/react-native-twitter-signin/issues/127
https://github.com/react-native-twitter-signin/twitter-signin


CODE
1. add these in your react native file
```
import RNTwitterSignIn from '@react-native-twitter-signin/twitter-signin';
const Constants = { 
  TWITTER_COMSUMER_KEY: "your-api-key",
  TWITTER_CONSUMER_SECRET: "your-api-key-secret"
}
```
```
 const signInWithTwitter = () => {
    RNTwitterSignIn.init(Constants.TWITTER_COMSUMER_KEY, Constants.TWITTER_CONSUMER_SECRET);
    RNTwitterSignIn.logIn()
      .then((loginData: any) => {
        const { authToken, authTokenSecret } = loginData;
        console.log(loginData);
        if (authToken && authTokenSecret) {
          ;
        }
      })
      .catch((error: any) => {
        console.log(error);
      }
    )
  }
```
```
<Button onPress={signInWithTwitter} />
```
2. check the callback url that @aryalprakash had mentioned above

3. in terminal (main folder)
```
yarn add @react-native-twitter-signin/twitter-signin
npx react-native link @react-native-twitter-signin/twitter-signin
```

4. clean and reinstall for node_module and pod
```
rm -rf node_modules
yarn
cd ios & rm -rf Pods
cd iOS
pod install
cd ..
```

5. add the following in info.plist
```
<key>CFBundleURLTypes</key>
<array>
<dict>
	<key>CFBundleTypeRole</key>
	<string>Editor</string>
	<key>CFBundleURLName</key>
	<string>xxxxxx</string>
	<key>CFBundleURLSchemes</key>
	<array>
		<string>com.googleusercontent.apps.xxxxx</string>
	</array>
</dict>
<dict>
	<key>CFBundleURLSchemes</key>
	<array>
		<string>fbxxxxx</string>
		<string>twitterkit-(your api key)</string>
	</array>
</dict>
</array>
```
```
<key>LSApplicationQueriesSchemes</key>
<array>
<string>fbapi</string>
              ...
<string>twitter</string>
<string>twitterauth</string>
</array>
```
6. add these in Podfile
```
pod 'TwitterKit5'
```
7. in AppDelegate.m
```
#import <TwitterKit/TWTRKit.h>

- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
    return YES;
  }

  if ([[Twitter sharedInstance] application:app openURL:url options:options]){
    return YES;
  }

  return NO;
}
```

Hope this help !
