### ISSUE TITLE
Asian Own....Can you accept pull requests to incorporate enhancements?

### ISSUE THREAD

**Issue by juanlet** [GoldenOwlAsia/react-native-twitter-signin#98]
It would be nice for Asian Owl to incorporate the pull requests that contains important features. Does anyone know how to contact him?

**Comment by 0paIescent** [comment]
I agree, @thethanghn if you are unable to continue maintenance of this package I believe the responsible thing to do is either allow some contributors direct access to accept pull requests, or announce that you are unable to continue supporting it. 

Either way, I'm going to be setting up my own fork of this repository so that I can start fixing these issues that, frankly, need to fixed asap. @juanlet I understand you too are using this package enough to want things fixed, when I get my fork up and fixed I'll be sure to let you know!

**Comment by juanlet** [comment]
@0paIescent  of course. We all need to use this great package, so count me in. We need to contribute between each other to keep things going.

**Comment by thethanghn** [comment]
@juanlet you can add my skype `sc.thangnt` for faster response.
